repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c8bad492e1b1d65d9126dba3fe3bd49a5a52b9d6 # v2.1.0
    hooks:
    -   id: end-of-file-fixer
        files: CMakeLists.txt|configure.ac|Makefile.am|\.xml$|\.yml$
        exclude: src/IPhreeqcPhast/IPhreeqc/phreeqcpp/test.xml$|Doxygen/DoxygenLayout.xml$
    -   id: trailing-whitespace
        files: CMakeLists.txt|configure.ac|Makefile.am|\.xml$|\.yml$
        exclude: src/IPhreeqcPhast/IPhreeqc/phreeqcpp/test.xml$|Doxygen/DoxygenLayout.xml$
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, master, --branch, develop]
